apiVersion: v1
kind: PersistentVolume
metadata:
  name: mysql-persistent-storage
  namespace: wordpress
spec:
  capacity:
    storage: 1Gi
  accessModes:
    - ReadWriteMany
  mountOptions:
  - hard
  - nfsvers=4.1
  nfs:
    path: /mysql
    server: nfs-server

---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: mysql-persistent-storage
  namespace: wordpress
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: standard
  resources:
    requests:
      storage: 1Gi





