apiVersion: v1
kind: Service
metadata:
  labels:
    app: wordpress
  name: wordpress-mysql
  namespace: wordpress
spec:
  ports:
  - port: 3306
    protocol: TCP
    targetPort: 3306
  clusterIP: None
  selector:
    app: wordpress
    tier: mysql
status:
  loadBalancer: {}
