apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
      app: wordpress
  name: wordpress-mysql
  namespace: wordpress
spec:
  replicas: 1
  selector:
    matchLabels:
        app: wordpress
        tier: mysql
  template:
    metadata:
      labels:
          app: wordpress
          tier: mysql
    spec:
      volumes:
      - name: mysql-persistent-storage-vol
        persistentVolumeClaim:
          claimName: mysql-persistent-storage-pvc
      containers:
      - env:
        - name: MYSQL_ROOT_PASSWORD
          valueFrom:
            secretKeyRef:
              name: mysql-pass
              key: password
        ports:
        - containerPort: 3306
          name: mysql
        image: mysql:5.7
        name: mysql
        volumeMounts:
        - name: mysql-persistent-storage-vol
          mountPath: "/var/lib/mysql"
