apiVersion: v1
kind: PersistentVolume
metadata:
  name: nfs
  namespace: wordpress
spec:
  capacity:
    storage: 10Gi
  storageClassName: "standard"
  accessModes:
    - ReadWriteMany
  nfs:
    server: nfs-server.wordpress.svc.cluster.local
    path: "/exports"

---
kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: nfs
  namespace: wordpress
spec:
  accessModes:
    - ReadWriteMany
  storageClassName: "standard"
  resources:
    requests:
      storage: 5Gi
