apiVersion: apps/v1
kind: Deployment
metadata:
  name: nfs-server
  namespace: wordpress
spec:
  replicas: 1
  selector:
    matchLabels:
      role: nfs-server
  template:
    metadata:
      labels:
        role: nfs-server
    spec:
      containers:
          #- name: make-files
          #image: busybox
          #command: 
          #- "/bin/sh"
          #- "-c"
          #- "mkdir -p /exports/myt"
          #- "mkdir -p /exports/tyt"
          #volumeMounts:
          #- name: mypvc
          #  mountPath: /exports 
      - name: nfs-server
        image: gcr.io/google_containers/volume-nfs:0.8
        ports:
          - name: nfs
            containerPort: 2049
          - name: mountd
            containerPort: 20048
          - name: rpcbind
            containerPort: 111
        #command: ["/bin/sh", "-c"]
        #- "mkdir -p mysql"
        #args: ["mkdir /exports/mysql"]
        securityContext:
          privileged: true
        volumeMounts:
          - mountPath: /exports
            name: mypvc
      volumes:
        - name: mypvc
          gcePersistentDisk:
            pdName: nfsdisk1
            fsType: ext4
