apiVersion: v1
kind: PersistentVolume
metadata:
  name: wordpress-persistent-storage
  namespace: wordpress
spec:
  capacity:
    storage: 2Gi
  accessModes:
    - ReadWriteMany
  storageClassName: "nfs"
  #mountOptions:
  #  - hard
  #  - nfsvers=4.1
  nfs:
    path: "/exports/html"
    server: nfs-server.wordpress.svc.cluster.local

---

apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: wordpress-persistent-storage
  namespace: wordpress
spec:
  accessModes:
    - ReadWriteMany
  storageClassName: "nfs"
  resources:
    requests:
      storage: 1Gi
