apiVersion: v1
kind: PersistentVolume
metadata:
  name: wordpress-persistent-storage
  namespace: wordpress
spec:
  capacity:
    storage: 1Gi
  accessModes:
    - ReadWriteMany
  mountOptions:
    - hard
    - nfsvers=4.1
  nfs:
    path: /html
    server: nfs-server

---

apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: wordpress-persistent-storage-pvc
  namespace: wordpress
spec:
  accessModes:
    - ReadWriteMany
  storageClassName: "standard"
  resources:
    requests:
      storage: 1Gi
